### PR TITLE
Fix condition AllReplicasReady

### LINKED ISSUE #261: AllReplicasReady outputs True although no pod created
## Describe the bug
RabbitMQ cluster condition `AllReplicasReady` outputs `True` although no pod got created.

## To Reproduce
1. `make deploy-kind`
2. `kubectl apply -f cr-example.yaml` where cf-example.yaml contains
```
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: example
  namespace: default
spec:
  affinity: {}
  image: rabbitmq
  imagePullSecret: my-secret
  persistence:
    storage: 10Gi
  replicas: 1
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: "1"
      memory: 2Gi
  service:
    type: ClusterIP
  tolerations:
  - {}
``` 
3. `kubectl describe statefulsets.apps example-rabbitmq-server`
will output the following event since no pod could be created:
```
Warning  FailedCreate      31s (x15 over 113s)  statefulset-controller  create Pod example-rabbitmq-server-0 in StatefulSet example-rabbitmq-server failed error: Pod "example-rabbitmq-server-0" is invalid: spec.tolerations[0].operator: Invalid value: "": operator must be Exists when `key` is empty, which means "match all values and all keys"
```

```
kubectl get pods
No resources found in default namespace.
```

However, `kubectl describe rabbitmqcluster example`
outputs
```
  Conditions:
    Last Transition Time:  2020-08-20T13:39:55Z
    Reason:                AllPodsAreReady
    Status:                 True
    Type:                  AllReplicasReady
```

**Expected behavior**
`kubectl describe rabbitmqcluster example`
should output
```
  Conditions:
    Last Transition Time:  2020-08-20T13:39:55Z
    Message:             0/1 Pods ready
    Reason:                NotAllPodsReady
    Status:                False
    Type:                  AllReplicasReady
```

## Version information
- RabbitMQ: 3.8.5
- RabbitMQ Cluster Operator: https://github.com/rabbitmq/cluster-operator/commit/cccfcb4f724a08472a216f51a948923f524b16c0
- Kubernetes: 1.17.5
 
## Additional context
This bug occurs because https://github.com/rabbitmq/cluster-operator/blob/fba823feaf43b4419511c6f8872dcfeb4d0f3da8/internal/status/all_replicas_ready.go#L40 compares `Status.Replicas` with  `Status.ReadyReplicas`. However, the former "is the number of Pods created by the StatefulSet controller". What we want instead is `StatefulSetSpec.Replicas` which is the desired number of replicas.

### PR DESCRIPTION
**Pull request by ansd**
This closes #261

### CODE REVIEW

File: internal/status/all_replicas_ready_test.go [hunk 1]
```diff
@@ -107,23 +108,23 @@ var _ = Describe("AllReplicasReady", func() {
...
 				})
 
 				It("updates the transition time", func() {
-					condition := rabbitmqstatus.AllReplicasReadyCondition([]runtime.Object{&corev1.Endpoints{}, sts}, existingCondition)
+					condition := rabbitmqstatus.AllReplicasReadyCondition([]runtime.Object{&corev1.Endpoints{}, sts}, oldCondition)
 					Expect(condition.LastTransitionTime).ToNot(Equal(emptyTime))
 				})
 			})
 
 			When("transitions to false", func() {
```
Comment (harshac) [inline internal/status/all_replicas_ready_test.go:120]: I know it's not a change made by this PR but a suggestion. -
The transition to false or true does not really seem to have a previous state. The test blocks are a bit confusing. We can merge these with the `When` blocks above where another `It` could be verifying that the transition time is set. It's upto you.

File: internal/status/all_replicas_ready_test.go [hunk 2]
```diff
@@ -153,32 +154,32 @@ var _ = Describe("AllReplicasReady", func() {
...
+					condition := rabbitmqstatus.AllReplicasReadyCondition([]runtime.Object{sts}, oldCondition)
 
-					Expect(existingCondition).NotTo(BeNil())
-					existingConditionTime := existingCondition.LastTransitionTime.DeepCopy()
+					Expect(oldCondition).NotTo(BeNil())
+					oldConditionTime := oldCondition.LastTransitionTime.DeepCopy()
 
-					Expect(condition.LastTransitionTime.Equal(existingConditionTime)).To(BeFalse())
-					Expect(condition.LastTransitionTime.Before(existingConditionTime)).To(BeFalse())
+					Expect(condition.LastTransitionTime.Equal(oldConditionTime)).To(BeFalse())
```
Comment (harshac) [inline internal/status/all_replicas_ready_test.go:166]: Can we replace the matcher to use Equal instead of BeFalse and BeTrue? Is there a reason for not doing that?

**Review by ChunyiLyu — APPROVED** [review]
LGTM
