### PR TITLE
Requeue when conflict on status update

### LINKED ISSUE #472: Controller error "the object has been modified"
## Describe the bug
When creating a new RabbitMQ cluster, sporadically, the controller logs show:
```
2020-11-17T09:07:28.109Z	ERROR	controller	Reconciler error	{"reconcilerGroup": "rabbitmq.com", "reconcilerKind": "RabbitmqCluster", "controller": "rabbitmqcluster", "name": "example", "namespace": "default", "error": "Operation cannot be fulfilled on rabbitmqclusters.rabbitmq.com \"example\": the object has been modified; please apply your changes to the latest version and try again"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:246
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:218
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.6.3/pkg/internal/controller/controller.go:197
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:155
k8s.io/apimachinery/pkg/util/wait.BackoffUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:156
k8s.io/apimachinery/pkg/util/wait.JitterUntil
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:133
k8s.io/apimachinery/pkg/util/wait.Until
	/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/util/wait/wait.go:90
```

## To Reproduce
Deploy RabbitMQ a couple of times
```bash
for i in $(seq 0 19); do kubectl rabbitmq create "rabbitmq-$i"; done
```
and check the controller logs.

## Version information
- RabbitMQ Cluster Operator: latest `main`:  https://github.com/rabbitmq/cluster-operator/commit/60f24b8341d1c08c8c9f2483f915df58d0abdbb8
- Kubernetes: 1.19
 
## Additional context
Understand why we see these errors.
Are we missing `clientretry.RetryOnConflict` somewhere or do we need to adapt the `Backoff` parameters?

### PR DESCRIPTION
**Pull request by ansd**
Fixes #472.

The error described in the issue occurred sporadically when updating the RabbitMQ status subresource in https://github.com/rabbitmq/cluster-operator/blob/06a015fa05bf67e2b01777055e3bfdb4cd4ec575/controllers/rabbitmqcluster_controller.go#L126

It occurred when creating a new cluster. It occurred in the 2nd reconcile iteration running very shortly after the 1st reconcile iteration which already updates the status subresource in https://github.com/rabbitmq/cluster-operator/blob/06a015fa05bf67e2b01777055e3bfdb4cd4ec575/controllers/rabbitmqcluster_controller.go#L203

If a conflict occurs when updating the status subresource, I decided to simply requeue the key instead of using `clientretry.RetryOnConflict`. The latter option would be very confusing because the controller would need to fetch the same (but updated) CR again that was already fetched at the start of the reconcile loop.

### CODE REVIEW

**Review by ablease — APPROVED** [review]
LGTM David 👍

File: controllers/rabbitmqcluster_controller.go [hunk 1]
```diff
@@ -113,19 +113,12 @@ func (r *RabbitmqClusterReconciler) Reconcile(req ctrl.Request) (ctrl.Result, er
 		}
 	}
 
-	childResources, err := r.getChildResources(ctx, *rabbitmqCluster)
+	requeueAfter, err := r.updateStatus(ctx, rabbitmqCluster)
 	if err != nil {
 		return ctrl.Result{}, err
 	}
```
Comment (Zerpet) [inline controllers/rabbitmqcluster_controller.go:119]: Perhaps we can merge the `if` conditions as `if err != nil || requeueAfter > 0` and always return with `RequeueAfter` ?

In the case of `err = nill` and `requeueAfter = 2`, we will requeue without printin the stack trace; otherwise we will requeue after 0 and print the error. I believe it is the same behaviour.

Comment (ansd) [reply controllers/rabbitmqcluster_controller.go]: Oh yes good spot, thanks @Zerpet :)

Looking at https://github.com/kubernetes-sigs/controller-runtime/blob/2b423ec0a6646ad7fec022f76aa7c94358dc1135/pkg/internal/controller/controller.go#L261-L282, merging both branches / conditions has the same behaviour.

**Review by Zerpet — APPROVED** [review]
